language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: correct-horse-66
  api_key:
    secure: DKjiAE17LgUbsn+Mtnr92JafosAb1PieOlT8VyJrJO04pMsNG5b8dgZJBTnV4wTvaqtnCXjTUyiPQethJLaWS4f5E+ZanHXs5CQzuWJjUmmcOPf7dLVj+s3nOAM3rNUkNqZ+sjiRRsKfF+0LjjmL6s4kGr70qOG/bu8eECg8z7eSIt8zmn0tppprLSp2LW2M7mrO4QihK9Kp2E6duAqnql0uFng6R0VOO5pkchFtksjwt9fXqkLy84NODiv+7r6suJf1YWbsX38vvO5cGMt43V6dGY1Y6glBJ8GMUT1r+CcXYKIOTlx96Dic3GNM0JCzCjSr+Tt6DEI7x7u0Lj5GAa+fQvYCN1aTGglCdE9i8zDl2s1M6tFgkXEL2wDGGAeWtVCuJjp5v4iKkHUwRmO9C/xKpyo0BStuEOsf3ZKJDNGWQCXbczqOnMAwvLonj4Xe2INn9AI/7ozqRkSS1gz7vOnb72l/NmZIhGX/GtRNteykvjSrUtDeLpA/Bf1ioEMjxbJkDP3rT0Y7xTq5ZkmsLjPMZ2jYAYgyd+Q98xj+nYKKD8QYchejK9632wzLUWdqVISqrCCySq1Qx9/b1ZDOhhClfCkMGwFGcDM/Wq599ZiazU3j/Lw8/0gHZN4OYchRdxXnx41DFiXKnvszdnWMcZvepTF69TgZUYlA6rJegvg=
