language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: correct-horse-66
  api_key:
    secure: CLZqQefANvG5ow8wfLF3HOdFNlrYsmU6GH8znym3u9nlE/84bYcumYnbbFipTkS4AmRy2QNmNoirM448OB3zkg8vC1+FlhjXvC/ovAx6u16v4w04BvNh8frmkjiBnFNGRP9xLGFLTJCdf00XsQUPGPngMYJKAaBzeEtm5CJZ0hq0tftLTtt4Zk5ptGMoPwynBtyXRE6LKeEHO0ik4++24peZka5Hn76UrgN7dxsscWSZ3aT24wvMk3UJ/vAVIAHPPowZznaddDWcfZ9XtkwjmNWgj6XqOdW8UlbR82Y+bFWza0C0NYNVKKYaSRznKbSzP8oMG3Ls2MpzvA13PP5csU9gsn5Dvb4dejILk3Gjnl401IDE5BJZl6ZVS5wMowO6r8GyzZZqCvPZG4QlIeKfD5rO9QlTWt/8s3NPdWYP+6yH0D0UTAbEi+uTELKa8i95Lu4TPy1ZR6CRwdxziFjYUda6+94LDwpp2FQvap9qd5i+WQgEXqp0650dbK1VfczuzSofW+JFlPG4ddW0JhJyJWM68OPdKbQq4Ql3VjGZXNZRaJYjPtGazvrKQ0hFcgtrOA12JD3Id3WxkFCH303PDxNetml5UBIO6tzR31na91zuwdt4JrrCp5JL6vNEWUdEQ6g5bkLzpAwHOZ4LHklQn7mSJ2/mYnNA0cskf1M7HpE=
